### ISSUE TITLE
IllegalStateException when trying to run (cljs-repl)

### ISSUE THREAD

**Issue by settinghead** [weavejester/duct#21] opened 2015-11-27 01:17 UTC
I received the following error when trying to run `(cljs-repl)`:
```
IllegalStateException Can't change/establish root binding of: *cljs-repl-env* with set  clojure.lang.Var.set (Var.java:221)
```

Steps to reproduce:
```bash
lein new duct foobar +cljs
cd foobar
lein setup
lein repl
```

```
> (go)
Compiling "target/figwheel/foobar/public/js/main.js" from ["src" "dev"]...
notifying browser that file changed:  target/figwheel/foobar/public/js/goog/deps.js
notifying browser that file changed:  target/figwheel/foobar/public/js/cljs_deps.js
notifying browser that file changed:  out/cljs/user.js
Successfully compiled "target/figwheel/foobar/public/js/main.js" in 4.684 seconds.
> (cljs-repl)
IllegalStateException Can't change/establish root binding of: *cljs-repl-env* with set  clojure.lang.Var.set (Var.java:221)
```

**Comment by weavejester** [comment] 2015-11-27 01:33
I can't reproduce this. Do you have anything in your `~/.lein/profiles.clj` file that could be causing a dependency conflict?

Typically you also probably want to use `+cljs` with `+site`. Otherwise you don't get all the middleware used for building websites, and you don't get an index page with the ClojureScript files loading in. This means that `(cljs-repl)` won't be able to connect (though it shouldn't raise an exception, it should just block).

**Comment by settinghead** [comment] 2015-11-27 02:22
@weavejester Thanks for the pointers. 

I did some more experiments:

1. I removed my entire `~/.lein` and `~/.m2` directory on my OS X and re-played the steps (I also added ```+site``` though I don't think it is the cause as you have described.
2. I started a clean VM with Linux Mint, installed Leiningen and JVM from scratch and replay the steps.

In both scenarios, I'm seeing the same `IllegalStateException` exception.

I remember being able to run `(cljs-repl)` a few weeks ago (perhaps on a previous version of duct), but unfortunately am not able to find out exactly which version.

**Comment by weavejester** [comment] 2015-11-27 03:35
Could you post the `project.clj` file that's created, and the results of `lein deps :tree`?

**Comment by weavejester** [comment] 2015-11-27 03:46
Ah, wait, I've managed to reproduce it. I'm investigating...

**Comment by weavejester** [comment] 2015-11-27 03:56
It turns out that the Cider plugin in my `profiles.clj` was making it work for me. Once I cleared my own `~/.lein` and `~/.m2` directories I could reproduce the error.

In your `project.clj` file, try changing the line:

    :middleware [cemerick.piggieback/wrap-cljs-repl]

To:

    :nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]

And tell me if that fixes your issue. If it does, I'll update the template accordingly.

Thanks for reporting this, and your investigation into it.

**Comment by settinghead** [comment] 2015-11-27 04:14
Yes, applying the above change to my `project.clj` solved the issue. :+1: 

Thanks for providing the fix!

**Comment by weavejester** [comment] 2015-11-27 16:21
Opening issue since it's not yet fixed in the template.

**Closed** 2015-11-27 16:26 UTC
